tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/core"

tap 'goles/battery'
tap 'uptech/homebrew-oss'

# The commented out ones were installed manually (brew doesn't like that)
# cask '1password'
# cask 'alacritty'
# cask 'authy'
# cask 'brave-browser'
# cask 'dropbox'
cask 'gimp'
# cask 'google-chrome'
# cask 'slack'
cask 'spotify'
cask 'vlc'
cask 'workflowy'
# cask 'zoom' # This is not zoom.us

brew 'uptech/oss/alt'
brew 'battery'
brew 'diff-so-fancy'
brew 'fswatch'
brew 'fzf'
brew 'gcc'
brew 'git'
brew 'git-town'
brew 'neovim'
brew 'nginx'
brew 'node'
brew 'openssl'
brew 'postgresql'
brew 'python'
brew 'python3'
brew 'rbenv'
brew 'readline'
brew 'redis'
brew 'ruby'
brew 'sbt'
brew 'scala'
brew 'spark'
brew 'sphinx-doc'
brew 'terminal-notifier'
brew 'the_silver_searcher'
brew 'tmux'
brew 'yarn'
brew 'zsh'
brew 'zsh-completions'
brew 'zsh-syntax-highlighting'

